### ISSUE TITLE
FATAL: password authentication failed for user "admin"

### ISSUE THREAD

**Issue by SwiftNet2024** [LogicLabs-OU/OpenArchive#177]
**Describe the bug**
OS: Debian 13.1
After editing the .env file and starting the docker instance, the web page (http://localhost:3000) isn't accessible.
Logs show the postgresql authentication for user "admin" fails.

**To Reproduce**
Launching the docker instance is all that is needed to recreate the error.

**Expected behavior**
The expected behaviour is to see the "setup" web page at http://localhost:3000
**Screenshots**

**System:**
 - Open Archiver Version:  v.0.3.4

**Relevant logs:**

"sudo docker logs 2d4b57504d44"

PostgreSQL Database directory appears to contain a database; Skipping initialization

2025-10-10 16:15:10.326 UTC [1] LOG:  starting PostgreSQL 17.6 on x86_64-pc-linux-musl, compiled by gcc (Alpine 14.2.0) 14.2.0, 64-bit
2025-10-10 16:15:10.327 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2025-10-10 16:15:10.327 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2025-10-10 16:15:10.329 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2025-10-10 16:15:10.333 UTC [29] LOG:  database system was interrupted; last known up at 2025-10-10 16:14:52 UTC
2025-10-10 16:15:10.833 UTC [29] LOG:  database system was not properly shut down; automatic recovery in progress
2025-10-10 16:15:10.834 UTC [29] LOG:  invalid record length at 0/1959DE0: expected at least 24, got 0
2025-10-10 16:15:10.834 UTC [29] LOG:  redo is not required
2025-10-10 16:15:10.836 UTC [27] LOG:  checkpoint starting: end-of-recovery immediate wait
2025-10-10 16:15:10.843 UTC [27] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.002 s, sync=0.002 s, total=0.008 s; sync files=2, longest=0.001 s, average=0.001 s; distance=0 kB, estimate=0 kB; lsn=0/1959DE0, redo lsn=0/1959DE0
2025-10-10 16:15:10.846 UTC [1] LOG:  database system is ready to accept connections
2025-10-10 16:15:16.860 UTC [33] FATAL:  password authentication failed for user "admin"
2025-10-10 16:15:16.860 UTC [33] DETAIL:  Connection matched file "/var/lib/postgresql/data/pg_hba.conf" line 128: "host all all all scram-sha-256"
2025-10-10 16:15:19.882 UTC [34] FATAL:  password authentication failed for user "admin"
2025-10-10 16:15:19.882 UTC [34] DETAIL:  Connection matched file "/var/lib/postgresql/data/pg_hba.conf" line 128: "host all all all scram-sha-256"
2025-10-10 16:15:22.528 UTC [35] FATAL:  password authentication failed for user "admin"
2025-10-10 16:15:22.528 UTC [35] DETAIL:  Connection matched file "/var/lib/postgresql/data/pg_hba.conf" line 128: "host all all all scram-sha-256"
2025-10-10 16:15:25.257 UTC [36] FATAL:  password authentication failed for user "admin"
2025-10-10 16:15:25.257 UTC [36] DETAIL:  Connection matched file "/var/lib/postgresql/data/pg_hba.conf" line 128: "host all all all scram-sha-256"
2025-10-10 16:15:28.333 UTC [37] FATAL:  password authentication failed for user "admin"
2025-10-10 16:15:28.333 UTC [37] DETAIL:  Connection matched file "/var/lib/postgresql/data/pg_hba.conf" line 128: "host all all all scram-sha-256"
2025-10-10 16:15:32.320 UTC [38] FATAL:  password authentication failed for user "admin"
2025-10-10 16:15:32.320 UTC [38] DETAIL:  Connection matched file "/var/lib/postgresql/data/pg_hba.conf" line 128: "host all all all scram-sha-256"
2025-10-10 16:15:37.849 UTC [39] FATAL:  password authentication failed for user "admin"
2025-10-10 16:15:37.849 UTC [39] DETAIL:  Connection matched file "/var/lib/postgresql/data/pg_hba.conf" line 128: "host all all all scram-sha-256"
2025-10-10 16:15:46.598 UTC [40] FATAL:  password authentication failed for user "admin"
2025-10-10 16:15:46.598 UTC [40] DETAIL:  Connection matched file "/var/lib/postgresql/data/pg_hba.conf" line 128: "host all all all scram-sha-256"
2025-10-10 16:16:01.700 UTC [47] FATAL:  password authentication failed for user "admin"
2025-10-10 16:16:01.700 UTC [47] DETAIL:  Connection matched file "/var/lib/postgresql/data/pg_hba.conf" line 128: "host all all all scram-sha-256"
2025-10-10 16:16:29.688 UTC [49] FATAL:  password authentication failed for user "admin"
2025-10-10 16:16:29.688 UTC [49] DETAIL:  Connection matched file "/var/lib/postgresql/data/pg_hba.conf" line 128: "host all all all scram-sha-256"
2025-10-10 16:17:23.267 UTC [50] FATAL:  password authentication failed for user "admin"
2025-10-10 16:17:23.267 UTC [50] DETAIL:  Connection matched file "/var/lib/postgresql/data/pg_hba.conf" line 128: "host all all all scram-sha-256"
2025-10-10 16:18:25.634 UTC [51] FATAL:  password authentication failed for user "admin"
2025-10-10 16:18:25.634 UTC [51] DETAIL:  Connection matched file "/var/lib/postgresql/data/pg_hba.conf" line 128: "host all all all scram-sha-256"
2025-10-10 16:19:27.950 UTC [53] FATAL:  password authentication failed for user "admin"
2025-10-10 16:19:27.950 UTC [53] DETAIL:  Connection matched file "/var/lib/postgresql/data/pg_hba.conf" line 128: "host all all all scram-sha-256"
2025-10-10 16:20:30.287 UTC [54] FATAL:  password authentication failed for user "admin"
2025-10-10 16:20:30.287 UTC [54] DETAIL:  Connection matched file "/var/lib/postgresql/data/pg_hba.conf" line 128: "host all all all scram-sha-256"
2025-10-10 16:21:24.892 UTC [1] LOG:  received fast shutdown request
2025-10-10 16:21:24.893 UTC [1] LOG:  aborting any active transactions
2025-10-10 16:21:24.894 UTC [1] LOG:  background worker "logical replication launcher" (PID 32) exited with exit code 1
2025-10-10 16:21:24.894 UTC [27] LOG:  shutting down
2025-10-10 16:21:24.895 UTC [27] LOG:  checkpoint starting: shutdown immediate
2025-10-10 16:21:24.898 UTC [27] LOG:  checkpoint complete: wrote 0 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.001 s, sync=0.001 s, total=0.004 s; sync files=0, longest=0.000 s, average=0.000 s; distance=0 kB, estimate=0 kB; lsn=0/1959E90, redo lsn=0/1959E90
2025-10-10 16:21:24.902 UTC [1] LOG:  database system is shut down

**Additional context**
The temp fix for FATAL: password authentication failed for user "admin" 
Login to the postgresql container, type: psql -U admin -d open_archive This will get you in and you can change the password to whatever is in the .env, here is an example:  ALTER USER admin WITH PASSWORD 'myuniquepassword';  Now the web portal works BUT I'm not sure how to make this permanent.

**Comment by weishest** [comment]
Avoid any special characters in the PG password should fix this problem

**Comment by SwiftNet2024** [comment]
Thanks, originally I thought that was the case but I changed the password to alphanumeric and it still failed.
